default_title: Babel 

meta_keywords: "Babel,Babel kenya,e-commerce software kenya,kenyan online shops,kenyan web developers,top kenyan developers"

meta_description: "Babel designs simple focused beautiful software.See everything like never before"